# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05b2978cc7d4bb9b680aaf80fbbf758c0fedd7c56d54d81cc22951a931cb4ca211a573facb0d6bec80925afda35724801b557a65c4ac9fb9a33f9ba41a046d80

test:
  secret_key_base: 079503dd2bcba3d5ad134528d1eba7199ba36134add0aabb0ac775c47f13bafd1f2c8e61fde5b9ff52440a7242d6e8b68c7ed24781366e85ac62f8a7d83ebbca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
